#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2025 Western Digital Corporation or its affiliates.
#
# Test test_device_array()

. tests/meta/rc

DESCRIPTION="exit with non-zero status from test_device_array()"

test_device_array() {
	echo "Running ${TEST_NAME}"
	echo "Test complete"
	return 1
}
