#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2025 Oracle and/or its affiliates
#
# Test SCSI Atomic Writes with MD devices

. tests/scsi/rc
. common/scsi_debug
. common/xfs

DESCRIPTION="test md atomic writes"
QUICK=1

requires() {
	_have_driver scsi_debug
	_stacked_atomic_test_requires
}

test() {
	local scsi_debug_params=(
		delay=0
		atomic_wr=1
		num_tgts=1
		add_host=4
		per_host_store=true
	)

	echo "Running md_atomics_test"

	if ! _configure_scsi_debug "${scsi_debug_params[@]}"; then
		return 1
	fi

	_md_atomics_test "${SCSI_DEBUG_DEVICES[0]}" "${SCSI_DEBUG_DEVICES[1]}" \
			"${SCSI_DEBUG_DEVICES[2]}" "${SCSI_DEBUG_DEVICES[3]}"

	_exit_scsi_debug

	echo "Test complete"
}
